# Generated by Django 3.2.9 on 2022-01-05 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0002_alter_lottery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lottery',
            name='date',
            field=models.CharField(max_length=150),
        ),
    ]
