# Generated by Django 3.2.9 on 2023-01-07 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0004_alter_lottery_plate_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lottery',
            name='lottery_number',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
